[package]
name = "xiapi"
version = "0.1.3"
edition = "2021"
rust-version = "1.59.0"
license = "MIT"
description = "High-level API bindings for XIMEA Cameras"
homepage = "https://www.ximea.com"
repository = "https://github.com/Ximea-GmbH/xiapi"
readme = "README.md"
keywords = ["ximea", "bindings", "camera", "image"]
categories = ["api-bindings"]

[dependencies]
xiapi-sys = "0.1.1"
paste = "1.0.6"
image = { version = "0.24.2", optional= true}
libc = "0.2"

[dev-dependencies]
serial_test = { version = "2.0.0", features = ["file_locks"] }
approx = "0.5.1"

[[example]]
name = "xi_sample"
path = "examples/xi_sample.rs"

[features]
default = ["image"]
image = ["dep:image"]